### ISSUE TITLE
Missing From Spoof

### ISSUE THREAD

**Issue by spec1re** [fmbla/spamassassin-fromnamespoof#2]
Hi, I'm using you plugin and I like it, but some From Spoof is missing when address part of FROM contains more than one mail, maybe you can have look?

[FROM_SPOOF_SENDER.txt](https://github.com/fmbla/spamassassin-fromnamespoof/files/2374089/FROM_SPOOF_SENDER.txt)

Thanks.

**Comment by steadramon** [comment]
Hi,

There's a possibility that increasing fns_extrachars from the default of 5 will help, though this may also increase False Positives

**Comment by spec1re** [comment]
fns_extrachars 11

Works for this sample, anything I should be aware with fns_extrachars 11?

Thanks!

**Comment by steadramon** [comment]
Only thing to be aware is that the rule may fire more on legit emails that have a from name spoof.

Yeah, the plugin will be maintained there from now on! :)


Paul
